[rf]
device_name = zmq
device_args = tx_port=tcp://127.0.0.1:2002,rx_port=tcp://127.0.0.1:2003,base_srate=5.76e6

[rat.nr]
pdsch.nof_prb = 106
ssb.scs = 30
nof_carriers = 1

[rrc]
release = 17

[usim]
mode = soft
algo = milenage
imsi = 001010123456780
imei = 353490069873319
k = 00112233445566778899AABBCCDDEEFF
opc = 63BFA50EE6523365FF14C1F45F88737D

[nas]
apn = internet
apn_protocol = ipv4

[gw]
netns = ue1
ip_devname = uesimtun0

[pcap]
enable = true
filename = ./outputs/pcap/ue.pcap

[log]
filename = ./outputs/logs/ue/ue.log
all_level = info

; TODO(version-check): confirm section names for installed srsUE release
