#!/usr/bin/env bash
set -euo pipefail
source "$(cd "$(dirname "$0")" && pwd)/common.sh"

if [[ "$(uname -s)" != "Linux" ]]; then
  die "This bootstrap script must be run inside Ubuntu Linux or WSL Ubuntu."
fi

if [[ ! -f /etc/os-release ]]; then
  die "Unable to detect Linux distribution."
fi

source /etc/os-release
if [[ "${ID:-}" != "ubuntu" ]]; then
  die "Unsupported distro: ${ID:-unknown}. Use Ubuntu 22.04 or 24.04."
fi

UBUNTU_CODENAME="${VERSION_CODENAME:-}"
if [[ "$UBUNTU_CODENAME" != "jammy" && "$UBUNTU_CODENAME" != "noble" ]]; then
  die "Unsupported Ubuntu release: ${VERSION_ID:-unknown}. Use 22.04 or 24.04."
fi

if [[ "$UBUNTU_CODENAME" == "noble" ]]; then
  log "WARNING: Open5GS package-manager installation is documented most clearly for Ubuntu 22.04 (Jammy)."
  log "WARNING: Ubuntu 24.04 (Noble) may still work, but if package resolution fails, prefer Ubuntu 22.04 or add a source-build fallback."
fi

DEBIAN_FRONTEND=noninteractive
export DEBIAN_FRONTEND

OMNETPP_VERSION="${OMNETPP_VERSION:-6.0.3}"
OMNETPP_ROOT_DEFAULT="${HOME}/opt/omnetpp-${OMNETPP_VERSION}"
OMNETPP_TARBALL="${HOME}/.cache/5g-nr-sitl/omnetpp-${OMNETPP_VERSION}-linux-x86_64.tgz"
OMNETPP_DOWNLOAD_URL="${OMNETPP_DOWNLOAD_URL:-https://github.com/omnetpp/omnetpp/releases/download/omnetpp-${OMNETPP_VERSION}/omnetpp-${OMNETPP_VERSION}-linux-x86_64.tgz}"
OMNETPP_ENABLE_OSG="${OMNETPP_ENABLE_OSG:-1}"
OMNETPP_ENABLE_OSGEARTH="${OMNETPP_ENABLE_OSGEARTH:-0}"
PYTHON_VENV="${PROJECT_ROOT}/.venv"
SRSRAN_PROJECT_SRC="${HOME}/src/srsRAN_Project"
SRSRAN_4G_SRC="${HOME}/src/srsRAN_4G"

cleanup_stale_srsran_ppas() {
  if [[ "$UBUNTU_CODENAME" != "noble" ]]; then
    return 0
  fi
  log "Removing stale srsRAN Launchpad PPA entries that do not publish Noble Release files."
  sudo_if_needed rm -f \
    /etc/apt/sources.list.d/softwareradiosystems-ubuntu-srsran-project-*.list \
    /etc/apt/sources.list.d/softwareradiosystems-ubuntu-srsran-project-*.sources \
    /etc/apt/sources.list.d/softwareradiosystems-ubuntu-srsran_4g-*.list \
    /etc/apt/sources.list.d/softwareradiosystems-ubuntu-srsran_4g-*.sources
}

install_base_packages() {
  cleanup_stale_srsran_ppas
  log "Installing base Ubuntu packages and build/runtime dependencies."
  sudo_if_needed apt-get update
  sudo_if_needed apt-get install -y \
    software-properties-common curl wget git ca-certificates gnupg lsb-release \
    python3 python3-pip python3-venv build-essential cmake make pkg-config \
    tcpdump tshark wireshark iproute2 iptables iperf3 jq net-tools \
    libzmq3-dev libczmq-dev gnuradio flex bison dirmngr qtbase5-dev qtchooser \
    qt5-qmake qtbase5-dev-tools libqt5opengl5-dev libfftw3-dev libsctp-dev \
    libyaml-cpp-dev libmbedtls-dev libboost-program-options-dev libconfig++-dev \
    libgtest-dev ninja-build libopenscenegraph-dev
}

install_omnetpp_python_modules() {
  log "Installing Python modules required by OMNeT++ configure/IDE checks."
  sudo_if_needed apt-get install -y python3-pandas python3-posix-ipc || true

  if ! python3 -c "import pandas, posix_ipc" >/dev/null 2>&1; then
    log "Falling back to pip for missing OMNeT++ Python modules."
    python3 -m pip install --user pandas posix_ipc >/dev/null 2>&1 || \
      python3 -m pip install --user --break-system-packages pandas posix_ipc
  fi
}

prepare_omnetpp_config() {
  local configure_user="${OMNETPP_ROOT_DEFAULT}/configure.user"
  local with_osg="yes"
  local with_osgearth="no"
  if [[ "${OMNETPP_ENABLE_OSG}" != "1" ]]; then
    with_osg="no"
  fi
  if [[ "${OMNETPP_ENABLE_OSGEARTH}" == "1" ]]; then
    with_osgearth="yes"
  fi

  mkdir -p "${OMNETPP_ROOT_DEFAULT}"
  if [[ ! -f "${configure_user}" ]]; then
    cat > "${configure_user}" <<EOF
# Generated by 5g-nr-sitl bootstrap.
WITH_OSG=${with_osg}
WITH_OSGEARTH=${with_osgearth}
EOF
  else
    if ! grep -q '^WITH_OSG=' "${configure_user}"; then
      printf '\nWITH_OSG=%s\n' "${with_osg}" >> "${configure_user}"
    else
      sed -i "s/^WITH_OSG=.*/WITH_OSG=${with_osg}/" "${configure_user}"
    fi
    if ! grep -q '^WITH_OSGEARTH=' "${configure_user}"; then
      printf 'WITH_OSGEARTH=%s\n' "${with_osgearth}" >> "${configure_user}"
    else
      sed -i "s/^WITH_OSGEARTH=.*/WITH_OSGEARTH=${with_osgearth}/" "${configure_user}"
    fi
  fi
}

install_open5gs() {
  log "Installing Open5GS from the official PPA."
  sudo_if_needed add-apt-repository -y ppa:open5gs/latest
  sudo_if_needed apt-get update
  sudo_if_needed apt-get install -y open5gs
}

install_mongodb() {
  log "Installing MongoDB Community and mongosh."
  curl -fsSL "https://pgp.mongodb.com/server-8.0.asc" | \
    sudo_if_needed gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor
  echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu ${UBUNTU_CODENAME}/mongodb-org/8.0 multiverse" | \
    sudo_if_needed tee /etc/apt/sources.list.d/mongodb-org-8.0.list >/dev/null
  sudo_if_needed apt-get update
  sudo_if_needed apt-get install -y mongodb-org mongodb-mongosh
  sudo_if_needed apt-get install -y --fix-broken || true
  sudo_if_needed systemctl enable mongod
  sudo_if_needed systemctl start mongod
}

install_srsran_packages() {
  log "Installing srsRAN Project and srsRAN 4G packages."
  sudo_if_needed add-apt-repository -y ppa:softwareradiosystems/srsran-project
  sudo_if_needed add-apt-repository -y ppa:softwareradiosystems/srsran_4g
  sudo_if_needed apt-get update
  sudo_if_needed apt-get install -y srsran-project srsran_4g
}

build_srsran_project_from_source() {
  log "Building srsRAN Project from source with ZMQ enabled."
  mkdir -p "$(dirname "${SRSRAN_PROJECT_SRC}")"
  if [[ ! -d "${SRSRAN_PROJECT_SRC}/.git" ]]; then
    git clone --depth 1 https://github.com/srsran/srsRAN_Project.git "${SRSRAN_PROJECT_SRC}"
  else
    git -C "${SRSRAN_PROJECT_SRC}" pull --ff-only
  fi
  cmake -S "${SRSRAN_PROJECT_SRC}" -B "${SRSRAN_PROJECT_SRC}/build" -DENABLE_EXPORT=ON -DENABLE_ZEROMQ=ON
  cmake --build "${SRSRAN_PROJECT_SRC}/build" -j"$(nproc)"
  sudo_if_needed cmake --install "${SRSRAN_PROJECT_SRC}/build"
  sudo_if_needed ldconfig
}

build_srsran_4g_from_source() {
  log "Building srsRAN 4G from source for srsUE."
  mkdir -p "$(dirname "${SRSRAN_4G_SRC}")"
  if [[ ! -d "${SRSRAN_4G_SRC}/.git" ]]; then
    git clone --depth 1 https://github.com/srsran/srsRAN_4G.git "${SRSRAN_4G_SRC}"
  else
    git -C "${SRSRAN_4G_SRC}" pull --ff-only
  fi
  cmake -S "${SRSRAN_4G_SRC}" -B "${SRSRAN_4G_SRC}/build"
  cmake --build "${SRSRAN_4G_SRC}/build" -j"$(nproc)"
  sudo_if_needed cmake --install "${SRSRAN_4G_SRC}/build"
  sudo_if_needed ldconfig
  command -v srsran_4g_install_configs.sh >/dev/null 2>&1 && srsran_4g_install_configs.sh user || true
}

install_or_build_srsran() {
  if [[ "$UBUNTU_CODENAME" == "jammy" ]]; then
    install_srsran_packages
    return 0
  fi

  log "Ubuntu ${VERSION_ID:-unknown} detected. Falling back to source builds for srsRAN Project and srsRAN 4G."
  build_srsran_project_from_source
  build_srsran_4g_from_source
}

install_python_env() {
  log "Creating Python virtual environment for the testbed."
  python3 -m venv "${PYTHON_VENV}"
  "${PYTHON_VENV}/bin/pip" install --upgrade pip
  "${PYTHON_VENV}/bin/pip" install -r "${PROJECT_ROOT}/requirements.txt"
}

install_omnetpp() {
  if [[ -d "${OMNETPP_ROOT_DEFAULT}" ]]; then
    log "OMNeT++ already present at ${OMNETPP_ROOT_DEFAULT}."
  else
    log "Installing OMNeT++ ${OMNETPP_VERSION}."
    mkdir -p "$(dirname "${OMNETPP_TARBALL}")" "$(dirname "${OMNETPP_ROOT_DEFAULT}")"
    if [[ ! -f "${OMNETPP_TARBALL}" ]]; then
      curl -L "${OMNETPP_DOWNLOAD_URL}" -o "${OMNETPP_TARBALL}"
    fi
    tar -xzf "${OMNETPP_TARBALL}" -C "$(dirname "${OMNETPP_ROOT_DEFAULT}")"
  fi

  prepare_omnetpp_config

  if [[ ! -x "${OMNETPP_ROOT_DEFAULT}/bin/opp_makemake" ]]; then
    log "Building OMNeT++ runtime tools."
    (
      cd "${OMNETPP_ROOT_DEFAULT}"
      set +u
      source ./setenv
      set -u
      ./configure
      make -j"$(nproc)"
    )
  fi
}

write_env_file() {
  log "Generating project .env with compatibility defaults."
  sed \
    -e "s#^PROJECT_ROOT=.*#PROJECT_ROOT=${PROJECT_ROOT}#" \
    -e "s#^OMNETPP_ROOT=.*#OMNETPP_ROOT=${OMNETPP_ROOT_DEFAULT}#" \
    -e "s#^OPEN5GS_CONFIG_DIR=.*#OPEN5GS_CONFIG_DIR=${PROJECT_ROOT}/configs/core#" \
    -e "s#^OPEN5GS_SUBSCRIBERS_FILE=.*#OPEN5GS_SUBSCRIBERS_FILE=${PROJECT_ROOT}/configs/core/subscribers.yaml#" \
    -e "s#^SRSRAN_GNB_CONFIG=.*#SRSRAN_GNB_CONFIG=${PROJECT_ROOT}/configs/gnb/gnb_zmq_compat.yaml#" \
    -e "s#^SRSRAN_UE_CONFIG=.*#SRSRAN_UE_CONFIG=${PROJECT_ROOT}/configs/ue/ue_zmq_compat.conf#" \
    -e "s#^GNURADIO_CHANNEL_PROFILE=.*#GNURADIO_CHANNEL_PROFILE=${PROJECT_ROOT}/configs/channel/bypass_compat.yaml#" \
    -e "s#^NR_PROFILE=.*#NR_PROFILE=${PROJECT_ROOT}/configs/nr_profiles/bootstrap_compat_mu0_15k.yaml#" \
    -e "s#^STATE_FILE=.*#STATE_FILE=${PROJECT_ROOT}/outputs/runtime/state.json#" \
    -e "s#^STATE_ENV_FILE=.*#STATE_ENV_FILE=${PROJECT_ROOT}/outputs/runtime/omnetpp.env#" \
    -e "s#^EVENT_LOG=.*#EVENT_LOG=${PROJECT_ROOT}/outputs/runtime/events.jsonl#" \
    -e "s#^METRICS_FILE=.*#METRICS_FILE=${PROJECT_ROOT}/outputs/runtime/metrics.json#" \
    "${PROJECT_ROOT}/.env.example" > "${PROJECT_ROOT}/.env"
}

build_omnetpp_project() {
  log "Building the local OMNeT++ visualization project."
  export OMNETPP_ROOT="${OMNETPP_ROOT_DEFAULT}"
  bash "${PROJECT_ROOT}/omnetpp/build.sh"
}

run_post_install_setup() {
  log "Applying network setup and Open5GS subscriber provisioning."
  bash "${PROJECT_ROOT}/scripts/setup_host_network.sh"
  PATH="${PYTHON_VENV}/bin:${PATH}" PYTHONPATH="${PROJECT_ROOT}" \
    python3 -m tools.provision_subscribers \
    --subscribers "${PROJECT_ROOT}/configs/core/subscribers.yaml" \
    --db-uri "mongodb://127.0.0.1/open5gs"
}

start_stack_if_requested() {
  if [[ "${AUTO_START_STACK:-1}" != "1" ]]; then
    return 0
  fi
  export OMNETPP_ROOT="${OMNETPP_ROOT_DEFAULT}"
  export PATH="${PYTHON_VENV}/bin:${PATH}"
  log "Starting the SITL stack."
  bash "${PROJECT_ROOT}/scripts/start_all.sh"
  if [[ "${AUTO_RUN_HEALTHCHECK:-1}" == "1" ]]; then
    bash "${PROJECT_ROOT}/scripts/healthcheck.sh" || true
  fi
}

install_base_packages
install_omnetpp_python_modules
install_mongodb
install_open5gs
install_or_build_srsran
install_python_env
install_omnetpp
write_env_file
build_omnetpp_project
run_post_install_setup
start_stack_if_requested

log "Bootstrap completed."
log "Python venv: ${PYTHON_VENV}"
log "OMNeT++ root: ${OMNETPP_ROOT_DEFAULT}"
log "Project environment file: ${PROJECT_ROOT}/.env"
